[package]
name = "floating-distance"
version = "0.1.0"
authors = ["Asher Jingkong Chen"]
description = "Compute distance between floating-point vectors in Rust"
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/AsherJingkongChen/distance.git"
rust-version = "1.56.0"

[badges]
maintenance = { status = "actively-developed" }

[features]
# simd = []

[profile.release]
lto = true

[dev-dependencies]
rand = "0.8.5"
