name: Codecov

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: codecov/codecov-action@v3
