name: Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Rust toolchain v1.60.0
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.60.0
        override: true

    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov

    - name: Check compilation (--no-default-features)
      run: cargo check --no-default-features

    - name: Check compilation (--all-features)
      run: cargo check --all-features

    - name: Run tests (--no-default-features)
      run: cargo test --no-default-features

    - name: Run tests (cargo-llvm-cov, --all-features)
      run: cargo llvm-cov --all-features --lcov --output-path llvm-cov.info

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: llvm-cov.info
        fail_ci_if_error: true
